### ISSUE TITLE
eslint-config-godaddy: Mocha/JSON plugins

### ISSUE THREAD

**Issue by gingur** [godaddy/javascript#126]
Are these plugins required? I'm using the second approach defined [here](https://github.com/godaddy/javascript/tree/master/packages/eslint-config-godaddy#2-define-your-local-eslintrc-and-run-eslint-yourself) using a `.eslintrc` file and I get an error about [missing these dependencies](https://github.com/godaddy/javascript/blob/master/packages/eslint-config-godaddy/package.json#L31-L32).  I'm not using mocha in my project (using ava), and I'm not linting any json files, so having these dependencies seem overkill.

**Comment by msluther** [comment]
I don't disagree, but there's some equilibrium between having a common configuration for use and either having 9001 different combinations of configurations or a minmal set and folks needing to add their own plugins ~80% of the time.

Perhaps we should re-evaluate what the common configuration should be, maybe it's shifted away from needing mocha/json and we should sever those dependencies.

I would probably also be okay in general with some more bare-bones versions of these configs for folks not in the 80% (or whatever % it happens to be) to start from. e.g. maybe we have a `*-minimal` for each of the common configs and the ones without the `-minimal` suffix keep the more "optional but common" dependencies.

**Comment by gingur** [comment]
Looking at the usage, we use [1](https://github.com/godaddy/javascript/blob/master/packages/eslint-config-godaddy/index.js#L39) `mocha` related rule (out of [22](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/index.js#L5-L26)), and 0? `json` rules out of [4](https://github.com/azeemba/eslint-plugin-json/blob/master/src/index.js#L95-L98)?

I'm wondering if the [`extends`](https://eslint.org/docs/user-guide/configuring#extending-configuration-files) array would be a better way to apply these. Something like `{ "extends": ["plugin:godaddy/mocha", "plugin:godaddy/json] }"` which could **optionally** be added when defining a `.eslintrc` file (most common use case?)

**Comment by msluther** [comment]
I could see us doing something like that. I suspect that we might still want common sets of configuration though so people aren't needing to duplicate eslint configs across tons of packages.

As for the json rules, I suspect that when #88 went through we missed that it changes from the json plugin@1 to v2, which has real rules defined other than just "is it json" so that likely need to be fixed up here as well depending on what we decide to do.
